apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: load-app-comp1-3e8ec11d-27bf-47e2-b04d-b158c94440c3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: load-app-comp1-3e8ec11d-27bf-47e2-b04d-b158c94440c3
    app.kubernetes.io/part-of: load-app-3e8ec11d-27bf-47e2-b04d-b158c94440c3
  name: load-app-comp1-3e8ec11d-27bf-47e2-b04d-b158c94440c3
  namespace: load-253da8fa-d97e-4f24-ab58-4bba1e37d967-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: load-app-comp1-3e8ec11d-27bf-47e2-b04d-b158c94440c3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: load-app-comp1-3e8ec11d-27bf-47e2-b04d-b158c94440c3
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/test-images@sha256:a64fe0dc7afe8bff975daeb708c18f3fcc40506aef0062546afbb8d4fde3207a
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
